// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"WASDMovement","status":true,"description":"Make player move with WASD keys.","parameters":{}},
{"name":"DoS_DayCycle","status":true,"description":"Implements the daily cycle system for preparation → tower exploration → return to sister.","parameters":{"MaxDays":"30","DayVariable":"1","PhaseVariable":"2","ShowDayInMenu":"true","ShowDayOnMap":"true","MapWindowPosition":"Top Left"}},
{"name":"DoS_StatusSystem","status":true,"description":"Implements custom status parameters: Fatigue, Corruption, and Hope.","parameters":{"FatigueVariable":"3","CorruptionVariable":"4","HopeVariable":"5","ShowInStatus":"true","FatiguePenalty":"50","CorruptionThreshold":"80","HopeBonusThreshold":"70","ShowOnMap":"true","MapWindowOpacity":"200","MapWindowPosition":"Top Left"}}
];
